/* eslint max-len: 0 */
export const appName = 'upshot';
export const jwtKey = 'jwtToken';
export const hashTagPrefix = '#';
export const handlePrefix = '@';
export const saltRounds = 10;
export const defaultImageSizeLimit = 2000000;
export const profileDescriptionMaxLength = 140;
export const defaultDebounceTime = 500;
